/**
 * withPlantAssets.js – Expo Config Plugin
 *
 * WHAT THIS DOES (so you can learn!)
 * ───────────────────────────────────
 * Expo config plugins run during `npx expo prebuild` to modify the
 * native android/ and ios/ directories. This plugin does two things:
 *
 * 1. Adds `aaptOptions { noCompress "tflite", "gguf" }` to the
 *    android/app/build.gradle so the model files are NOT compressed
 *    in the APK. TFLite needs to memory-map the model file, which
 *    only works if the file is stored uncompressed.
 *
 * 2. Copies model files from `models/` directory into the Android
 *    assets folder (`android/app/src/main/assets/`) during prebuild.
 *    This way, the model files live OUTSIDE the android/ directory
 *    (which gets regenerated by prebuild) and are safely copied in.
 *
 * HOW EXPO CONFIG PLUGINS WORK
 * ────────────────────────────
 * - `withAppBuildGradle` → lets you modify android/app/build.gradle contents
 * - `withDangerousMod` → lets you run arbitrary filesystem operations
 * - These run during `npx expo prebuild` or when EAS builds your app
 */

const {
  withAppBuildGradle,
  withDangerousMod,
} = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

/**
 * Step 1: Add aaptOptions to build.gradle
 * This prevents Android from compressing .tflite and .gguf files.
 */
function withAaptNoCompress(config) {
  return withAppBuildGradle(config, (config) => {
    const buildGradle = config.modResults.contents;

    // Only add if not already present
    if (!buildGradle.includes("noCompress")) {
      // Insert aaptOptions block inside the android { } block
      config.modResults.contents = buildGradle.replace(
        /android\s*\{/,
        `android {
    aaptOptions {
        noCompress "tflite", "gguf"
    }`
      );
      console.log("[withPlantAssets] ✅ Added aaptOptions noCompress for tflite/gguf");
    } else {
      console.log("[withPlantAssets] ℹ️  aaptOptions already present, skipping");
    }

    return config;
  });
}

/**
 * Step 2: Copy model files from models/ to android assets
 */
function withModelAssetsCopy(config) {
  return withDangerousMod(config, [
    "android",
    async (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const modelsDir = path.join(projectRoot, "models");
      const assetsDir = path.join(
        projectRoot,
        "android",
        "app",
        "src",
        "main",
        "assets"
      );

      // Create assets directory if it doesn't exist
      if (!fs.existsSync(assetsDir)) {
        fs.mkdirSync(assetsDir, { recursive: true });
        console.log("[withPlantAssets] 📁 Created android assets directory");
      }

      // Copy each model file
      if (fs.existsSync(modelsDir)) {
        const files = fs.readdirSync(modelsDir);
        for (const file of files) {
          const src = path.join(modelsDir, file);
          const dest = path.join(assetsDir, file);

          // Check if file exists and is same size (skip if already copied)
          const srcStats = fs.statSync(src);
          if (fs.existsSync(dest)) {
            const destStats = fs.statSync(dest);
            if (destStats.size === srcStats.size) {
              console.log(`[withPlantAssets] ℹ️  ${file} already exists, skipping`);
              continue;
            }
          }

          fs.copyFileSync(src, dest);
          const sizeMB = (srcStats.size / (1024 * 1024)).toFixed(1);
          console.log(`[withPlantAssets] ✅ Copied ${file} (${sizeMB} MB) to android assets`);
        }
      } else {
        console.warn("[withPlantAssets] ⚠️  No models/ directory found at:", modelsDir);
      }

      return config;
    },
  ]);
}

/**
 * Main plugin export – chains both modifications
 */
function withPlantAssets(config) {
  config = withAaptNoCompress(config);
  config = withModelAssetsCopy(config);
  return config;
}

module.exports = withPlantAssets;
